## This file contains functions used for programming assignment 2 of
## R Programming
## https://class.coursera.org/rprog-010/human_grading/view/courses/973491/assessments/3/submissions
## The assignment is an exercise in using multiple environments to cache
## time-intensive calculations
##
## I validated these functions by calling the following sequence through the
## command line
## > mymatrix <- genmatrix(5000)
## > mymatrix2 <- makeCacheMatrix(mymatrix)
## > mysolvematrix <- cacheSolve(mymatrix2) #this takes quite some time
## > mysolvematrix <- cacheSolve(mymatrix2)
##
## the second time I call mysolvematrix it's instantaneous
##
##
##
################################################################################

## This function receives a matrix.  It is assumed that solve() works on
##   this matrix
## This function generates a list with four elements.  The elements named
##   set, get, setsolve, getsolve
makeCacheMatrix <- function(x = matrix()) {
    s <- NULL
    set <- function(y) {
        x <<- y
        s <<- NULL
    }
    get <- function() x
    setsolve <- function(solve) s <<- solve
    getsolve <- function() s
    list(set = set, get = get,
         setsolve = setsolve,
         getsolve = getsolve)
}

## This function receives a list generated by makeCacheMatrix, applies
## the solve function and stores the results in cache.  Thereafter when this
## function is called it retrieves the results from cache rather than re-
## calculating.
cacheSolve <- function(x, ...) {
    s <- x$getsolve()
    if(!is.null(s)) {
        message("getting cached data")
        return(s)
    }
    data <- x$get()
    s <- solve(data, ...)
    x$setsolve(s)
    s
}



################################################################################
## original example below, with Hussain Boxwala's additions located at
## https://class.coursera.org/rprog-010/forum/thread?thread_id=364
## these examples were provided as part of the assignment, and slightly altered
## by M. Boxwala.  I used them as templates to complete the exercise.

makeVector <- function(x = numeric()) {
    m <- NULL
    print(environment())
    evn <- environment()
    print(parent.env(evn))
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x
    setmean <- function(mean) m <<- mean
    getmean <- function() m
    getevn<- function() environment()
    list(set = set, get = get,
         setmean = setmean,
         getmean = getmean,
         getevn = getevn)
}

cachemean <- function(x, ...) {
    m <- x$getmean()
    if(!is.null(m)) {
        message("getting cached data")
        return(m)
    }
    data <- x$get()
    m <- mean(data, ...)
    x$setmean(m)
    m
}


################################################################################
## This function returns a matrix of random normal variables of dimension x by x
## Can be used to generate the matrix to test the above functions
genmatrix <-function(x) {
    y<- stats::rnorm(x^2)
    dim(y) <- c(x,x)
    y
}